// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b3cbb0c99274521 "Bakalarka", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-WULUCIWK.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-AFD5BXR3.js";
import { stdin_default as stdin_default4 } from "./chunks/chunk-XCKNQFQV.js";
import { stdin_default } from "./chunks/chunk-I2OZVXB3.js";
import { stdin_default as stdin_default5 } from "./chunks/chunk-EAEJSXPP.js";
import "./chunks/chunk-3FZQO4KW.js";
import "./chunks/chunk-DG4N4X2W.js";
import { routes } from "./chunks/chunk-GZZHFEEK.js";

// virtual:desktop-all
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/uHSC8ROY2QRIYnZR2xmH/NGBo8u0p7i4NpQSOFxgJ/udk6C1VTY.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Image,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var HeaderFonts = getFonts(stdin_default2);
var ButtonFonts = getFonts(stdin_default);
var TabsFonts = getFonts(stdin_default4);
var ProductCardFonts = getFonts(stdin_default3);
var FooterFonts = getFonts(stdin_default5);
var cycleOrder = ["dPXyJKT80", "kCvllqT5u", "ZlhkQOdB_"];
var serializationHash = "framer-ZHTwD";
var variantClassNames = {
	dPXyJKT80: "framer-v-1z18lm",
	kCvllqT5u: "framer-v-1669if9",
	ZlhkQOdB_: "framer-v-197q983",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "dPXyJKT80",
	Phone: "ZlhkQOdB_",
	Tablet: "kCvllqT5u",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "dPXyJKT80",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "dPXyJKT80",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	const isDisplayed = () => {
		if (baseVariant === "ZlhkQOdB_") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "ZlhkQOdB_") return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "kCvllqT5u") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (["kCvllqT5u", "ZlhkQOdB_"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1z18lm",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"dPXyJKT80"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								kCvllqT5u: {
									"data-framer-name": "Tablet",
								},
								ZlhkQOdB_: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={94}
							width={componentViewport?.width || "100vw"}
							{...addPropertyOverrides(
								{
									kCvllqT5u: {
										height: 100,
									},
									ZlhkQOdB_: {
										height: 70,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-pymjc1-container"}
								layoutDependency={layoutDependency}
								layoutId={"h70RIn2f3-container"}
								nodeId={"h70RIn2f3"}
								rendersWithMotion={true}
								scopeId={"udk6C1VTY"}
							>
								{_jsx(stdin_default2, {
									eH6MqNBad: "Co hled\xE1te?",
									height: "100%",
									id: "h70RIn2f3",
									layoutId: "h70RIn2f3",
									style: {
										width: "100%",
									},
									variant: "na0ZfXoX0",
									width: "100%",
									...addPropertyOverrides(
										{
											kCvllqT5u: {
												style: {
													height: "100%",
													width: "100%",
												},
											},
											ZlhkQOdB_: {
												style: {
													height: "100%",
													width: "100%",
												},
												variant: "Wt1Aibcil",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-1yn9159"}
							layoutDependency={layoutDependency}
							layoutId={"OCn9ZOoZJ"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 132.8,
									intrinsicWidth: 268.8,
									pixelHeight: 166,
									pixelWidth: 336,
									src: "https://framerusercontent.com/images/balwnVddUIvIngiRiBXxbJW3o.png",
								}}
								className={"framer-a2ugjy"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"XWQXOLFdP"}
							/>
							<motion.div
								className={"framer-yqq1w"}
								data-framer-name={"ProductInfo"}
								layoutDependency={layoutDependency}
								layoutId={"febARbD2d"}
							>
								<motion.div
									className={"framer-80h8di"}
									layoutDependency={layoutDependency}
									layoutId={"cALKfVUYQ"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1hoiv4s"}
										fonts={["Inter", "Inter-Bold"]}
										layoutDependency={layoutDependency}
										layoutId={"GvogivTTd"}
										style={{
											"--extracted-r6o4lv": "rgb(24, 31, 90)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												ZlhkQOdB_: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--framer-font-size": "30px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(24, 31, 90))",
																}}
															>
																<motion.strong>
																	{
																		'MacBook Pro 14" M4 PRO CZ 2024 Vesm\xEDrn\u011B \u010Dern\xFD'
																	}
																</motion.strong>
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--framer-font-size": "35px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(24, 31, 90))",
												}}
											>
												<motion.strong>
													{
														'MacBook Pro 14" M4 PRO CZ 2024 Vesm\xEDrn\u011B \u010Dern\xFD'
													}
												</motion.strong>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1gln0g6"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ma5sRxm5b"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												ZlhkQOdB_: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--framer-font-size": "17px",
																}}
															>
																{
																	'MacBook - Apple M4 Pro (12j\xE1drov\xFD), 14,2" Liquid Retina XDR leskl\xFD 3024 \xD7 1964 px, 120 Hz, RAM 24GB, Apple M4 PRO 16j\xE1drov\xE1 GPU, SSD 512GB, podsv\xEDcen\xE1 kl\xE1vesnice, webkamera, \u010Dte\u010Dka otisk\u016F prst\u016F, WiFi 6E, Bluetooth, hmotnost 1,6 kg, macOS'
																}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--framer-font-size": "20px",
												}}
											>
												{
													'MacBook - Apple M4 Pro (12j\xE1drov\xFD), 14,2" Liquid Retina XDR leskl\xFD 3024 \xD7 1964 px, 120 Hz, RAM 24GB, Apple M4 PRO 16j\xE1drov\xE1 GPU, SSD 512GB, podsv\xEDcen\xE1 kl\xE1vesnice, webkamera, \u010Dte\u010Dka otisk\u016F prst\u016F, WiFi 6E, Bluetooth, hmotnost 1,6 kg, macOS'
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-118zile"}
									layoutDependency={layoutDependency}
									layoutId={"EGCaEcyw_"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1b1rhep"}
										fonts={["Inter-Bold"]}
										layoutDependency={layoutDependency}
										layoutId={"X2DCjUHda"}
										style={{
											"--extracted-r6o4lv": "rgb(24, 31, 90)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItQm9sZA==",
													"--framer-font-family":
														'"Inter", "Inter Placeholder", sans-serif',
													"--framer-font-size": "30px",
													"--framer-font-weight": "700",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(24, 31, 90))",
												}}
											>
												{"59 990 K\u010D"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1f5u37g"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"BJz1ioR4F"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--framer-font-size": "17px",
													"--framer-text-alignment": "center",
												}}
											>
												{"bez DPH 49 579 K\u010D"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1lld16d"}
									layoutDependency={layoutDependency}
									layoutId={"EUNQJmwdX"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "Ow7zl50ff",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "Ow7zl50ff",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "Ow7zl50ff",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={60}
												width={`max((max(min(${componentViewport?.width || "100vw"}, 450px), 336px) - 10px) / 2, 1px)`}
												{...addPropertyOverrides(
													{
														ZlhkQOdB_: {
															width: `max((max(min(max(${componentViewport?.width || "100vw"}, 101px) - 50px, 450px), 336px) - 10px) / 2, 1px)`,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1ypnj6z-container"}
													layoutDependency={layoutDependency}
													layoutId={"p0n2sQgtX-container"}
													nodeId={"p0n2sQgtX"}
													rendersWithMotion={true}
													scopeId={"udk6C1VTY"}
												>
													{_jsx(stdin_default, {
														bfUSsO8bY: resolvedLinks[0],
														height: "100%",
														id: "p0n2sQgtX",
														Jmi2dMDKA: "Do ko\u0161\xEDku",
														layoutId: "p0n2sQgtX",
														style: {
															height: "100%",
															width: "100%",
														},
														variant: "Jcrvt7Mqm",
														width: "100%",
														...addPropertyOverrides(
															{
																kCvllqT5u: {
																	bfUSsO8bY: resolvedLinks[1],
																},
																ZlhkQOdB_: {
																	bfUSsO8bY: resolvedLinks[2],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "Ow7zl50ff",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "Ow7zl50ff",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "Ow7zl50ff",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={60}
												width={`max((max(min(${componentViewport?.width || "100vw"}, 450px), 336px) - 10px) / 2, 1px)`}
												{...addPropertyOverrides(
													{
														ZlhkQOdB_: {
															width: `max((max(min(max(${componentViewport?.width || "100vw"}, 101px) - 50px, 450px), 336px) - 10px) / 2, 1px)`,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-3eanyl-container"}
													layoutDependency={layoutDependency}
													layoutId={"PT_FT05iO-container"}
													nodeId={"PT_FT05iO"}
													rendersWithMotion={true}
													scopeId={"udk6C1VTY"}
												>
													{_jsx(stdin_default, {
														bfUSsO8bY: resolvedLinks1[0],
														height: "100%",
														id: "PT_FT05iO",
														Jmi2dMDKA: "Rezervovat",
														layoutId: "PT_FT05iO",
														style: {
															height: "100%",
															width: "100%",
														},
														variant: "deknpdK4G",
														width: "100%",
														...addPropertyOverrides(
															{
																kCvllqT5u: {
																	bfUSsO8bY: resolvedLinks1[1],
																},
																ZlhkQOdB_: {
																	bfUSsO8bY: resolvedLinks1[2],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-1jepdc1"}
							data-framer-name={"TabCOmponent"}
							layoutDependency={layoutDependency}
							layoutId={"OD0m3nhVI"}
						>
							<ComponentViewportProvider
								height={56}
								width={componentViewport?.width || "100vw"}
								{...addPropertyOverrides(
									{
										kCvllqT5u: {
											width: `calc(${componentViewport?.width || "100vw"} * 0.9664)`,
										},
										ZlhkQOdB_: {
											width: `calc(${componentViewport?.width || "100vw"} * 0.9413)`,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-sjuse7-container"}
									layoutDependency={layoutDependency}
									layoutId={"X6p2I2r74-container"}
									nodeId={"X6p2I2r74"}
									rendersWithMotion={true}
									scopeId={"udk6C1VTY"}
								>
									{_jsx(stdin_default4, {
										height: "100%",
										id: "X6p2I2r74",
										layoutId: "X6p2I2r74",
										style: {
											width: "100%",
										},
										variant: "ZbyG7Ukg_",
										width: "100%",
										...addPropertyOverrides(
											{
												kCvllqT5u: {
													variant: "hYHVRjhJ4",
												},
												ZlhkQOdB_: {
													variant: "kghn6hB1n",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion.div
								className={"framer-yrpex3"}
								data-framer-name={"Background"}
								layoutDependency={layoutDependency}
								layoutId={"WjjWrLkRq"}
								style={{
									backgroundColor: "rgb(244, 244, 244)",
								}}
							>
								<motion.div
									className={"framer-1cs0yb"}
									data-framer-name={"Deskcription"}
									layoutDependency={layoutDependency}
									layoutId={"QeAaxTNzz"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-w2d93k"}
										fonts={["Inter-Bold"]}
										layoutDependency={layoutDependency}
										layoutId={"vHhEbfOj_"}
										style={{
											"--extracted-r6o4lv": "rgb(24, 31, 90)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItQm9sZA==",
													"--framer-font-family":
														'"Inter", "Inter Placeholder", sans-serif',
													"--framer-font-size": "30px",
													"--framer-font-weight": "700",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(24, 31, 90))",
												}}
											>
												{"Popis produktu"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-10udh4x"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"dwZTcT_Cr"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--framer-font-size": "30px",
												}}
											>
												{'MacBook Pro 14" M4 Pro 12-CPU/16-GPU/24GB/512GB/SB'}
												<motion.br />
												{
													"Inovativn\xED \u010Dip generace Apple M4 & hardwarov\xE1 akcelerace sledov\xE1n\xED paprsk\u016F"
												}
												<motion.br />
												{
													"Strhuj\xEDc\xED Liquid Retina XDR displej s extr\xE9mn\xEDm dynamick\xFDm rozsahem"
												}
												<motion.br />
												{
													"Limitn\xED jas 1 600 nit\u016F, technologie True Tone & v\xEDce ne\u017E miliarda barev"
												}
												<motion.br />
												{
													"ProMotion s adaptivn\xED obnovovac\xED frekvenc\xED a\u017E 120 Hz"
												}
												<motion.br />
												{
													"Apple Inteligence* \u2013 pr\u016Flomov\xFD syst\xE9m osobn\xED inteligence"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<ComponentViewportProvider
								{...addPropertyOverrides(
									{
										ZlhkQOdB_: {
											height: 415,
											width: "311px",
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-wxs801-container"}
									layoutDependency={layoutDependency}
									layoutId={"spcEQtiCP-container"}
									nodeId={"spcEQtiCP"}
									rendersWithMotion={true}
									scopeId={"udk6C1VTY"}
								>
									{_jsx(stdin_default3, {
										AAdjwFSzE: "86 990 K\u010D",
										height: "100%",
										id: "spcEQtiCP",
										layoutId: "spcEQtiCP",
										o8nCnlCZP:
											'MacBook - Apple M4 Pro (14j\xE1drov\xFD), 16,2" Liquid Retina XDR leskl\xFD 3456 \xD7 2234 px, 120 Hz, RAM 48GB, ...',
										rk7t_VS0X:
											'MacBook Pro 16" M4 Pro - Vesm\xEDrn\u011B \u010Dern\xFD ',
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "NEJiEqA2S",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						<motion.div
							className={"framer-lbqr6m"}
							layoutDependency={layoutDependency}
							layoutId={"FUPFQvNUJ"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-rxr036"}
								fonts={["Inter", "Inter-Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"CMEtOWG68"}
								style={{
									"--extracted-r6o4lv": "rgb(24, 31, 90)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "30px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(24, 31, 90))",
										}}
									>
										<motion.strong>
											{"Mohlo by v\xE1s zaj\xEDmat"}
										</motion.strong>
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-11dpfrr"}
							data-framer-name={"CardsRow"}
							layoutDependency={layoutDependency}
							layoutId={"E4iBMHXB7"}
						>
							{isDisplayed() && (
								<ComponentViewportProvider
									{...addPropertyOverrides(
										{
											ZlhkQOdB_: {
												height: 358,
												width: componentViewport?.width || "100vw",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1xochpe-container"}
										layoutDependency={layoutDependency}
										layoutId={"hIukmWkFQ-container"}
										nodeId={"hIukmWkFQ"}
										rendersWithMotion={true}
										scopeId={"udk6C1VTY"}
									>
										{_jsx(stdin_default5, {
											height: "100%",
											id: "hIukmWkFQ",
											layoutId: "hIukmWkFQ",
											style: {
												width: "100%",
											},
											variant: "rxnG4lKYf",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed1() && (
								<ComponentViewportProvider
									height={500}
									width={"410px"}
									{...addPropertyOverrides(
										{
											kCvllqT5u: {
												width: "365px",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1xxh9bo-container"}
										layoutDependency={layoutDependency}
										layoutId={"IYkl8Kii2-container"}
										nodeId={"IYkl8Kii2"}
										rendersWithMotion={true}
										scopeId={"udk6C1VTY"}
									>
										{_jsx(stdin_default3, {
											AAdjwFSzE: "86 990 K\u010D",
											height: "100%",
											id: "IYkl8Kii2",
											layoutId: "IYkl8Kii2",
											o8nCnlCZP:
												'MacBook - Apple M4 Pro (14j\xE1drov\xFD), 16,2" Liquid Retina XDR leskl\xFD 3456 \xD7 2234 px, 120 Hz, RAM 48GB, ...',
											rk7t_VS0X:
												'MacBook Pro 16" M4 Pro - Vesm\xEDrn\u011B \u010Dern\xFD ',
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Jd5fEWDK3",
											width: "100%",
											...addPropertyOverrides(
												{
													kCvllqT5u: {
														variant: "XI2dPTmlD",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed2() && (
								<ComponentViewportProvider
									{...addPropertyOverrides(
										{
											kCvllqT5u: {
												height: 500,
												width: "365px",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-wtpv4j-container"}
										layoutDependency={layoutDependency}
										layoutId={"kb391H6bq-container"}
										nodeId={"kb391H6bq"}
										rendersWithMotion={true}
										scopeId={"udk6C1VTY"}
									>
										{_jsx(stdin_default3, {
											AAdjwFSzE: "86 990 K\u010D",
											height: "100%",
											id: "kb391H6bq",
											layoutId: "kb391H6bq",
											o8nCnlCZP:
												'MacBook - Apple M4 Pro (14j\xE1drov\xFD), 16,2" Liquid Retina XDR leskl\xFD 3456 \xD7 2234 px, 120 Hz, RAM 48GB, ...',
											rk7t_VS0X:
												'MacBook Pro 16" M4 Pro - Vesm\xEDrn\u011B \u010Dern\xFD ',
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "XI2dPTmlD",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed3() && (
								<ComponentViewportProvider height={500} width={"410px"}>
									<SmartComponentScopedContainer
										className={"framer-cro5ob-container"}
										layoutDependency={layoutDependency}
										layoutId={"AE7sgzQjQ-container"}
										nodeId={"AE7sgzQjQ"}
										rendersWithMotion={true}
										scopeId={"udk6C1VTY"}
									>
										{_jsx(stdin_default3, {
											AAdjwFSzE: "86 990 K\u010D",
											height: "100%",
											id: "AE7sgzQjQ",
											layoutId: "AE7sgzQjQ",
											o8nCnlCZP:
												'MacBook - Apple M4 Pro (14j\xE1drov\xFD), 16,2" Liquid Retina XDR leskl\xFD 3456 \xD7 2234 px, 120 Hz, RAM 48GB, ...',
											rk7t_VS0X:
												'MacBook Pro 16" M4 Pro - Vesm\xEDrn\u011B \u010Dern\xFD ',
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Jd5fEWDK3",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed3() && (
								<ComponentViewportProvider height={500} width={"410px"}>
									<SmartComponentScopedContainer
										className={"framer-1gsazi8-container"}
										layoutDependency={layoutDependency}
										layoutId={"lMBWmJTUk-container"}
										nodeId={"lMBWmJTUk"}
										rendersWithMotion={true}
										scopeId={"udk6C1VTY"}
									>
										{_jsx(stdin_default3, {
											AAdjwFSzE: "86 990 K\u010D",
											height: "100%",
											id: "lMBWmJTUk",
											layoutId: "lMBWmJTUk",
											o8nCnlCZP:
												'MacBook - Apple M4 Pro (14j\xE1drov\xFD), 16,2" Liquid Retina XDR leskl\xFD 3456 \xD7 2234 px, 120 Hz, RAM 48GB, ...',
											rk7t_VS0X:
												'MacBook Pro 16" M4 Pro - Vesm\xEDrn\u011B \u010Dern\xFD ',
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Jd5fEWDK3",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.div>
						{isDisplayed1() && (
							<ComponentViewportProvider
								height={358}
								width={componentViewport?.width || "100vw"}
							>
								<SmartComponentScopedContainer
									className={"framer-5zumiv-container"}
									layoutDependency={layoutDependency}
									layoutId={"MNGtN01MV-container"}
									nodeId={"MNGtN01MV"}
									rendersWithMotion={true}
									scopeId={"udk6C1VTY"}
								>
									{_jsx(stdin_default5, {
										height: "100%",
										id: "MNGtN01MV",
										layoutId: "MNGtN01MV",
										style: {
											width: "100%",
										},
										variant: "rxnG4lKYf",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZHTwD.framer-5a4v07, .framer-ZHTwD .framer-5a4v07 { display: block; }",
	".framer-ZHTwD.framer-1z18lm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 70px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1559px; }",
	".framer-ZHTwD .framer-pymjc1-container, .framer-ZHTwD .framer-sjuse7-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-1yn9159 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; height: min-content; justify-content: space-evenly; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-a2ugjy { aspect-ratio: 2.0240963855421685 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 247px); max-width: 600px; overflow: visible; position: relative; width: 500px; }",
	".framer-ZHTwD .framer-yqq1w { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 450px; min-width: 336px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ZHTwD .framer-80h8di { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-1hoiv4s, .framer-ZHTwD .framer-1gln0g6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ZHTwD .framer-118zile { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 3px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-ZHTwD .framer-1b1rhep, .framer-ZHTwD .framer-1f5u37g, .framer-ZHTwD .framer-w2d93k, .framer-ZHTwD .framer-rxr036 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ZHTwD .framer-1lld16d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-1ypnj6z-container, .framer-ZHTwD .framer-3eanyl-container { flex: 1 0 0px; height: 60px; position: relative; width: 1px; }",
	".framer-ZHTwD .framer-1jepdc1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-yrpex3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-1cs0yb { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 523px; justify-content: flex-start; overflow: visible; padding: 30px 0px 124px 60px; position: relative; width: 1px; }",
	".framer-ZHTwD .framer-10udh4x { flex: 1 0 0px; height: 1px; max-height: 323px; max-width: 800px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ZHTwD .framer-wxs801-container { flex: none; height: 415px; position: relative; width: 311px; }",
	".framer-ZHTwD .framer-lbqr6m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-11dpfrr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 70px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZHTwD .framer-1xochpe-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-ZHTwD .framer-1xxh9bo-container, .framer-ZHTwD .framer-cro5ob-container, .framer-ZHTwD .framer-1gsazi8-container { flex: none; height: 500px; position: relative; width: 410px; }",
	".framer-ZHTwD .framer-wtpv4j-container { flex: none; height: 500px; position: relative; width: 365px; }",
	".framer-ZHTwD .framer-5zumiv-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }",
	".framer-ZHTwD.framer-v-1669if9.framer-1z18lm { gap: 58px; justify-content: flex-start; width: 834px; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-pymjc1-container { height: 100px; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-1jepdc1 { height: 527px; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-sjuse7-container { width: 97%; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-yrpex3 { height: 517px; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-1cs0yb { height: 461px; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-11dpfrr { gap: 21px; }",
	".framer-ZHTwD.framer-v-1669if9 .framer-1xxh9bo-container { width: 365px; }",
	".framer-ZHTwD.framer-v-197q983.framer-1z18lm { gap: 24px; width: 375px; }",
	".framer-ZHTwD.framer-v-197q983 .framer-pymjc1-container { height: 70px; order: 0; }",
	".framer-ZHTwD.framer-v-197q983 .framer-1yn9159 { flex-direction: column; min-width: 101px; order: 1; padding: 25px; }",
	".framer-ZHTwD.framer-v-197q983 .framer-a2ugjy { height: var(--framer-aspect-ratio-supported, 161px); width: 100%; }",
	".framer-ZHTwD.framer-v-197q983 .framer-yqq1w { flex: none; width: 100%; }",
	".framer-ZHTwD.framer-v-197q983 .framer-1jepdc1 { order: 3; }",
	".framer-ZHTwD.framer-v-197q983 .framer-sjuse7-container { width: 94%; }",
	".framer-ZHTwD.framer-v-197q983 .framer-yrpex3 { padding: 42px 0px 42px 0px; }",
	".framer-ZHTwD.framer-v-197q983 .framer-1cs0yb { height: 960px; }",
	".framer-ZHTwD.framer-v-197q983 .framer-10udh4x { flex: none; height: 323px; width: 296px; }",
	".framer-ZHTwD.framer-v-197q983 .framer-wxs801-container { order: 5; }",
	".framer-ZHTwD.framer-v-197q983 .framer-lbqr6m { order: 4; }",
	".framer-ZHTwD.framer-v-197q983 .framer-rxr036 { order: 0; }",
	".framer-ZHTwD.framer-v-197q983 .framer-11dpfrr { order: 6; }",
];
var Framerudk6C1VTY = withCSS(Component, css, "framer-ZHTwD");
var stdin_default6 = Framerudk6C1VTY;
Framerudk6C1VTY.displayName = "DesktopAll";
Framerudk6C1VTY.defaultProps = {
	height: 2304,
	width: 1559,
};
addPropertyControls(Framerudk6C1VTY, {
	variant: {
		options: ["dPXyJKT80", "kCvllqT5u", "ZlhkQOdB_"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerudk6C1VTY,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...HeaderFonts,
		...ButtonFonts,
		...TabsFonts,
		...ProductCardFonts,
		...FooterFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:desktop-all
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ZlhkQOdB_",
	md: "kCvllqT5u",
	"2xl": "dPXyJKT80",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b3cbb0c992745214a4b30ad0a70c33cfe052c2a657df72dba4580f9855ea179"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DesktopAllFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b3cbb0c992745214a4b30ad0a70c33cfe052c2a657df72dba4580f9855ea179"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var desktop_all_default = ComponentWithRoot;
export { desktop_all_default as default };
